name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: yarn install
        run: |
          yarn install

      - name: yarn install (internal modules)
        run: |
          yarn extensions:run_all install

      - name: build internal modules
        run: |
          yarn extensions:run_all build

      - name: yarn test
        run: |
          yarn lint
          yarn build
